/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
    './hooks/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#301400",
        "surface-container-highest": "#e0e3e6",
        "outline": "#76767f",
        "tertiary": "#060100",
        "secondary-container": "#e0dfdf",
        "primary-container": "#0d1b3e",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8eb",
        "surface-container": "#eceef1",
        "on-tertiary-fixed-variant": "#653d20",
        "primary": "#00020e",
        "outline-variant": "#c6c6cf",
        "on-secondary-container": "#626363",
        "on-secondary-fixed": "#1a1c1c",
        "on-primary-fixed": "#0b1a3d",
        "surface-variant": "#e0e3e6",
        "secondary-fixed": "#e3e2e2",
        "inverse-on-surface": "#eff1f4",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "surface-tint": "#515d84",
        "on-tertiary-container": "#ab7a58",
        "surface-bright": "#f7f9fc",
        "secondary": "#5e5e5f",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "secondary-fixed-dim": "#c7c6c6",
        "on-primary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "background": "#f7f9fc",
        "tertiary-fixed-dim": "#f4ba95",
        "inverse-surface": "#2d3133",
        "on-primary-container": "#7784ad",
        "on-surface-variant": "#45464e",
        "tertiary-container": "#321500",
        "on-background": "#191c1e",
        "primary-fixed-dim": "#b9c5f2",
        "surface-container-low": "#f2f4f7",
        "primary-fixed": "#dbe1ff",
        "tertiary-fixed": "#ffdcc6",
        "surface": "#f7f9fc",
        "on-primary-fixed-variant": "#39456b",
        "surface-dim": "#d8dadd",
        "on-secondary-fixed-variant": "#464747",
        "inverse-primary": "#b9c5f2"
      },
      fontFamily: {
        headline: ['var(--font-manrope)', 'Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        body: ['var(--font-inter)', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        label: ['var(--font-inter)', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        sans: ['var(--font-inter)', 'Inter', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem"
      }
    },
  },
  plugins: [],
};
